import React, { useState, memo } from 'react';
import {
  View,
  TouchableOpacity,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { useTheme } from '../../theme/ThemeContext';
import { Typography, Input, Button } from '../../shared/components';
import { useAuthStore } from '../../store/useAuthStore';
import { useToast } from '../../shared/components/molecules/Toast';
import { SafeAreaView } from 'react-native-safe-area-context';

export interface TwoFactorAuthScreenProps {
  onSuccess: () => void;
  onCancel?: () => void;
}

const TwoFactorAuthScreenComponent: React.FC<TwoFactorAuthScreenProps> = ({
  onSuccess,
  onCancel,
}) => {
  const { colors } = useTheme();
  const { verify2FA } = useAuthStore();
  const { showToast } = useToast();

  const [code, setCode] = useState('');
  const [useBackupCode, setUseBackupCode] = useState(false);
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState('');

  const handleVerify = async () => {
    if (!code.trim()) {
      setError(useBackupCode ? 'Enter your 8-digit backup code' : 'Enter 6-digit TOTP code');
      return;
    }

    setIsVerifying(true);
    setError('');

    try {
      const ok = await verify2FA(code.trim());
      if (ok) {
        showToast({ message: '2FA authentication successful!', type: 'success' });
        onSuccess();
      } else {
        setError('Invalid security code. Please try again.');
      }
    } catch {
      setError('Verification failed. Try again.');
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={styles.content}
      >
        {onCancel && (
          <TouchableOpacity onPress={onCancel} style={styles.backBtn}>
            <Typography variant="h3" color={colors.text}>
              ←
            </Typography>
          </TouchableOpacity>
        )}

        <View style={styles.header}>
          <Typography variant="h1" color={colors.text} bold>
            🔐 Two-Factor Auth
          </Typography>
          <Typography variant="body1" color={colors.textSecondary} style={styles.subtitle}>
            {useBackupCode
              ? 'Enter one of your emergency 8-digit backup security recovery codes.'
              : 'Enter the 6-digit verification code generated by your Authenticator App (Google Authenticator, 1Password, or Authy).'}
          </Typography>
        </View>

        <Input
          label={useBackupCode ? 'Emergency Backup Code' : '6-Digit TOTP Security Code'}
          placeholder={useBackupCode ? 'e.g. 9821-4432' : '123456'}
          value={code}
          onChangeText={(t) => {
            setCode(t);
            setError('');
          }}
          error={error}
          keyboardType={useBackupCode ? 'default' : 'number-pad'}
          maxLength={useBackupCode ? 12 : 6}
          autoFocus
        />

        <Button
          label="Authenticate"
          loading={isVerifying}
          onPress={handleVerify}
          fullWidth
          size="lg"
          style={styles.verifyBtn}
        />

        <TouchableOpacity
          onPress={() => {
            setUseBackupCode(!useBackupCode);
            setCode('');
            setError('');
          }}
          style={styles.switchModeBtn}
        >
          <Typography variant="body2" color={colors.primary} bold>
            {useBackupCode ? 'Use Authenticator App Instead' : 'Use Emergency Backup Code'}
          </Typography>
        </TouchableOpacity>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

export const TwoFactorAuthScreen = memo(TwoFactorAuthScreenComponent);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  backBtn: {
    position: 'absolute',
    top: 20,
    left: 20,
    padding: 8,
  },
  header: {
    marginBottom: 28,
  },
  subtitle: {
    marginTop: 8,
    lineHeight: 22,
  },
  verifyBtn: {
    marginTop: 16,
    marginBottom: 16,
  },
  switchModeBtn: {
    alignItems: 'center',
    paddingVertical: 8,
  },
});
